### ISSUE TITLE
Customized error pages (particularly for 404 and GameNotFoundExceptions) are needed

### ISSUE THREAD

**Issue by karlmdavis** [karlmdavis/rps-tourney#95]
And I really need to ensure that `GameNotFoundException`s get mapped as 404s, by the way.

**Comment by Tritoniwe** [comment]
Hi! I'd like to help you and resolve this issue, but i can't run project due to almost empty dev instruction. In my project we use spring @ExceptionHandler with custom errors.

**Comment by karlmdavis** [comment]
@Tritoniwe: See [README-DEVENV.md](https://github.com/karlmdavis/rps-tourney/blob/master/dev/README-DEVENV.md) for instructions on setting up a useable development environment.

Sorry this took so long, but I had a lot of things ahead of it in line, priority-wise.

**Comment by karlmdavis** [comment]
Resolved in #121.
